#ifndef LISK_CONSTANTS_H
#define LISK_CONSTANTS_H

#define NEED_NEXT_CHUNK 0x6866

#define MAX_BIP32_PATH 10
#define MAX_BIP32_PATH_LENGTH (4 * MAX_BIP32_PATH) + 1

#define TX_MODULE_ID_TOKEN 2
#define TX_MODULE_ID_MULTISIG 4
#define TX_MODULE_ID_DPOS 5
#define TX_MODULE_ID_LEGACY 1000

#define TX_ASSET_ID_TRANSFER 0
#define TX_ASSET_ID_REGISTER_MULTISIG_GROUP 0
#define TX_ASSET_ID_REGISTER_DELEGATE 0
#define TX_ASSET_ID_VOTE_DELEGATE 1
#define TX_ASSET_ID_UNLOCK_TOKEN 2
#define TX_ASSET_ID_RECLAIM 0

/*
#define TX_TYPE_1_CONSENSUS_REWARD 1
#define TX_TYPE_2_TRANSFER_TX 2
#define TX_TYPE_3_SET_ALIAS 3
#define TX_TYPE_4_REGISTER_CONSENSUS_NODE 4
#define TX_TYPE_5_JOIN_CONSENSUS 5
#define TX_TYPE_6_CANCEL_CONSENSUS 6
#define TX_TYPE_7_YELLOW_CARD 7
#define TX_TYPE_8_RED_CARD 8
#define TX_TYPE_9_UNREGISTER_CONSENSUS_NODE 9
#define TX_TYPE_10_BUSINESS_DATA 10
#define TX_TYPE_100_CREATE_CONTRACT 100
#define TX_TYPE_101_CALL_CONTRACT 101
#define TX_TYPE_102_DELETE_CONTRACT 102
#define TX_TYPE_103_TRANSFER_CONTRACT 103
*/

#define ENCODED_PUB_KEY 32
#define ADDRESS_HASH_LENGTH 20 // sha256(pubkey) -> first 20 bytes
#define ADDRESS_LISK32_LENGTH 41 // "lsk" + lisk32 encoded

#define MAX_DATA_LENGTH 64 // data field max 64 bytes

#define NETWORK_ID_LENGTH 32

#define DIGEST_LENGTH 32
#define SIGNATURE_LENGTH 64

#endif
